class: "configuration-menu"
items:
  - href: "/rodb/configuration/inputs"
    title: "Inputs"
  - href: "/rodb/configuration/parsers"
    title: "Parsers"
  - href: "/rodb/configuration/indexes"
    title: "Indexes"
  - href: "/rodb/configuration/services"
    title: "Services"
  - href: "/rodb/configuration/outputs"
    title: "Outputs"
