version: '3.8'

services:
  build:
    tty: true
    image: localhost/rodb:latest
    build:
      context: .
      dockerfile: ./build/docker/service.Dockerfile
    volumes:
      - $PWD/configs:/etc/configs
    command: --help
  countries:
    tty: true
    depends_on:
      - build
    image: localhost/rodb:latest
    command: --config=/var/config.yaml
    ports:
      - "3004:80"
    volumes:
      - $PWD/examples/countries:/var
  japanese-dictionary:
    tty: true
    depends_on:
      - build
    build:
      context: ./examples/japanese-dictionary
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: localhost/rodb:latest
    user: root:root
    ports:
      - "3001:80"
      - "3002:443"
    volumes:
      - japaneseDictionaryIndexes:/var
  people:
    tty: true
    depends_on:
      - build
    build:
      context: ./examples/people
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: localhost/rodb:latest
    user: root:root
    ports:
      - "3003:80"
    volumes:
      - peopleIndexes:/var
  zip-codes-tokyo:
    tty: true
    depends_on:
      - build
    build:
      context: ./examples/zip-codes-tokyo
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: localhost/rodb:latest
    ports:
      - "3000:80"
  e2e_tests:
    tty: true
    depends_on:
      - countries
      - japanese-dictionary
      - people
      - zip-codes-tokyo
    build:
      context: .
      dockerfile: ./build/docker/e2e.Dockerfile
  build:
    tty: true
    image: localhost/rodb:latest
    build:
      context: .
      dockerfile: ./build/docker/service.Dockerfile
    volumes:
      - $PWD/configs:/etc/configs
    command: --help
  docs:
    tty: true
    image: jekyll/jekyll:3.8
    command: jekyll serve --watch
    working_dir: /srv/jekyll/docs
    ports:
      - "4000:4000"
    volumes:
      - $PWD:/srv/jekyll
      - jekyllDependencies:/usr
  schema-doc:
    tty: true
    build:
      context: .
      dockerfile: ./build/docker/schema-doc/Dockerfile
    volumes:
      - $PWD:/rodb
volumes:
  japaneseDictionaryIndexes:
  peopleIndexes:
  jekyllDependencies:
