version: '3.8'

services:
  tests:
    tty: true
    image: localhost/rodb:latest
    build:
      context: .
      dockerfile: ./build/docker/service.Dockerfile
    volumes:
      - $PWD/configs:/etc/configs
    command: --config=/etc/configs/default.yaml --verbose
