version: '3.8'

services:
  tests:
    tty: true
    image: localhost/rodb:latest
    build:
      context: .
      dockerfile: ./build/docker/service.Dockerfile
    volumes:
      - $PWD/configs:/etc/configs
    command: --config=/etc/configs/default.yaml --verbose
  people:
    tty: true
    build:
      context: ./examples/people
      dockerfile: ./Dockerfile
    user: root:root
    ports:
      - "3003:80"
    volumes:
      - generatedIndexes:/var
  japanese-dictionary:
    tty: true
    build:
      context: ./examples/japanese-dictionary
      dockerfile: ./Dockerfile
    user: root:root
    ports:
      - "3001:80"
      - "3002:443"
    volumes:
      - generatedIndexes:/var
  zip-codes-tokyo:
    tty: true
    build:
      context: ./examples/zip-codes-tokyo
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
volumes:
  generatedIndexes:
