version: '3.8'

services:
  tests:
    tty: true
    image: localhost/rods:latest
    build:
      context: .
      dockerfile: ./build/docker/service.Dockerfile
  japanese-dictionary:
    tty: true
    build:
      context: ./examples/japanese-dictionary
      dockerfile: ./Dockerfile
    ports:
      - "3001:80"
  zip-codes-tokyo:
    tty: true
    build:
      context: ./examples/zip-codes-tokyo
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
