version: '3.8'

services:
  unit_tests:
    tty: true
    image: localhost/rodb:latest
    build:
      context: .
      dockerfile: ./build/docker/service.Dockerfile
    volumes:
      - $PWD/configs:/etc/configs
    command: --help
  e2e_tests:
    tty: true
    build:
      context: .
      dockerfile: ./build/docker/e2e.Dockerfile
