inputs:
  - name: dictionary
    type: xml
    path: ./JMdict.xml
    recordXpath: "//entry"
    properties:
      - name: writing
        parser: string
        xpath: "string(//keb[1])"
      - name: reading
        parser: string
        xpath: "string(//reb[1])"
      - name: translation
        parser: string
        xpath: "string(//gloss[not(@xml:lang)][1])"
indexes:
  - name: index
    type: map
    input: dictionary
    properties:
      - writing
      - reading
  - name: indexSearch
    type: wildcard
    path: /index/indexSearch.rodb
    input: dictionary
    properties:
      - translation
outputs:
  - name: output
    type: jsonArray
    input: dictionary
    parameters:
      word:
        property: writing
        index: index
        parser: string
      translation:
        property: translation
        index: indexSearch
        parser: string
services:
  - name: service
    type: http
    http:
      listen: ":80"
    https:
      listen: ":443"
      certificatePath: "/rodb.crt"
      privateKeyPath: "/rodb.key"
    errorsType: application/json
    routes:
      - path: "/"
        output: output
