inputs:
  - name: dictionary
    type: xml
    path: /srv/JMdict.xml
    recordXpath: "//entry"
    properties:
      - name: writing
        parser: string
        xpath: "string(//keb[1])"
      - name: reading
        parser: string
        xpath: "string(//reb[1])"
      - name: translation
        parser: string
        xpath: "string(//gloss[not(@xml:lang)][1])"
indexes:
  - name: indexFilter
    type: sqlite
    dsn: /var/indexFilter.rodb
    input: dictionary
    properties:
      - name: writing
        collate: binary
      - name: reading
        collate: binary
  - name: indexTranslation
    type: wildcard
    path: /var/indexTranslation.rodb
    input: dictionary
    properties:
      - translation
outputs:
  - name: output
    type: jsonArray
    input: dictionary
    parameters:
      word:
        property: writing
        index: indexFilter
        parser: string
      translation:
        property: translation
        index: indexTranslation
        parser: string
services:
  - name: service
    type: http
    http:
      listen: ":80"
    https:
      listen: ":443"
      certificatePath: "/etc/rodb.crt"
      privateKeyPath: "/etc/rodb.key"
    errorsType: application/json
    routes:
      - path: "/"
        output: output
