version: '3.8'

services:
  japanese-dictionary:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: ghcr.io/rodb-io/rodb:master
    user: root:root
    ports:
      - "3001:80"
      - "3002:443"
    volumes:
      - japaneseDictionaryIndexes:/var
volumes:
  japaneseDictionaryIndexes:
