version: '3.8'

services:
  people:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: ghcr.io/rodb-io/rodb:master
    user: root:root
    ports:
      - "3003:80"
    volumes:
      - peopleIndexes:/var
volumes:
  peopleIndexes:
