version: '3.8'

services:
  zip-codes-tokyo:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: ghcr.io/rodb-io/rodb:master
    ports:
      - "3000:80"
