type: object
additionalProperties: false
properties:
  foo:
    type: string
  bar:
    description: dgfdg [Deprecated - use dfgdfg instead] dfgdgf
  baz:
    description: dgfdg [Deprecated - use dfgdfg instead] dfgdgf
