$id: https://rodb.io/schema/yaml/schema.yaml
$schema: http://json-schema.org/draft-07/schema#
description: Configuration file for RODB
type: object
additionalProperties: false
properties:
  parsers:
    type: array
    description: |
      # Parsers

      TODO parsers introduction
      TODO repeat the default parsers config here

      ### Example:
      ```yaml
      parsers:
        - name: booleanYesNo
          type: boolean
          falseValues: ["No", "NO", "no"]
          trueValues: ["Yes", "YES", "yes"]
        - name: integerWithCommas
          type: integer
          ignoreCharacters: ","
        - name: shiftJisString
          type: string
          convertFromCharset: "Shift_JIS"
      ```
    items:
      anyOf:
        - $ref: ./parsers/integer.yaml
          title: integer
        - $ref: ./parsers/float.yaml
          title: float
        - $ref: ./parsers/boolean.yaml
          title: boolean
        - $ref: ./parsers/string.yaml
          title: string
        - $ref: ./parsers/split.yaml
          title: split
        - $ref: ./parsers/json.yaml
          title: json
  inputs:
    type: array
    items:
      type: object
  indexes:
    type: array
    items:
      type: object
  outputs:
    type: array
    items:
      type: object
  services:
    type: array
    items:
      type: object
