$id: https://rodb.io/schema/yaml/config.yaml
$schema: http://json-schema.org/draft-07/schema#
description: Configuration file for RODB
type: object
additionalProperties: false
properties:
  parsers:
    $ref: ./parsers/parsers.yaml
  inputs:
    $ref: ./inputs/inputs.yaml
  indexes:
    $ref: ./indexes/indexes.yaml
  outputs:
    $ref: ./outputs/outputs.yaml
  services:
    $ref: ./services/services.yaml
