name: Build and create release
on:
  push:
    tags: ['*']
jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build/ci/build.sh
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_USER: "${{ github.actor }}"
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          # Bugfix where git would return the commit message instead of the tag message
          ref: ${{ github.ref }}
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - run: ./build/ci/release.sh
